name: audioSampler
version: 0.0.1
author: ne4istb
description: Audio sampler written on Dart
dependencies:
  angular: "1.1.0"
  web_components: ">=0.8.0 <0.9.0"
  browser: ">=0.10.0+2 <0.11.0"
  http_server: ">=0.9.5+1 <0.10.0"
  intl: ">=0.8.7 <0.12.0"
  appengine: '>=0.2.1 <0.3.0'
dev_dependencies:
  unittest: ">=0.11.0+5 <0.12.0"
  mock: ">=0.11.0+2 <0.12.0"
transformers:
- angular:
    html_files:
      - lib/sampler/sampler.html
      - lib/trackLine/track-line.html
      - lib/sample/sample.html
      - lib/shareButton/share-button.html
